[package]
name = "clipstash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib/mod.rs"

[dependencies]
serde = { version = "*", features = ["derive"]}
serde_json = "*"